using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MouseLook : MonoBehaviour
{
    public float mouseSensitivity = 100f;

    public Transform playerBody;

    float xRotation = 0f;

    // Start is called before the first frame update
    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;
    }

    // Update is called once per frame
    void Update()
    {
        if (!PauseMenu.GameIsPaused) {
            if (Cursor.lockState != CursorLockMode.Locked) {
                Cursor.lockState = CursorLockMode.Locked;
                Cursor.visible = false;
            }
            float mouseX = Input.GetAxis("Mouse X") * mouseSensitivity * .5f;
            float mouseY = Input.GetAxis("Mouse Y") * mouseSensitivity * .5f;

            xRotation -= mouseY;
            xRotation = Mathf.Clamp(xRotation, -90f, 90f);

            transform.localRotation = Quaternion.Euler(xRotation, 0f, 0f);
            playerBody.Rotate(Vector3.up * mouseX);
        }
        else if (Cursor.lockState == CursorLockMode.Locked) { 
            Cursor.lockState = CursorLockMode.None;
            Cursor.visible = true;
        }
    }
}
